import { MenuItem } from './types'

export const menuItems: MenuItem[] = [
  {
    id: 'lamb-kabob-rice',
    name: 'Lamb Kabob with Rice',
    description: 'Char-grilled lamb kabob served over warm, seasoned rice for a hearty and satisfying meal.',
    price: 16.99,
    category: 'Rice Dishes',
    image_url: '/images/menu/lamb-kabob-rice.webp',
  },
  {
    id: 'kobidah-kabob-rice',
    name: 'Kobidah Kabob with Rice',
    description: 'Juicy, well-seasoned ground beef kobidah kabob grilled and served over rice.',
    price: 14.99,
    category: 'Rice Dishes',
    image_url: '/images/menu/kobidah-kabob-rice.webp',
  },
  {
    id: 'chicken-kabob-rice',
    name: 'Chicken Kabob with Rice',
    description: 'Tender, well-cooked chicken kabob grilled and served over rice.',
    price: 14.99,
    category: 'Rice Dishes',
    image_url: '/images/menu/chicken-kabob-rice.webp',
  },
  {
    id: 'gyro-rice',
    name: 'Gyro with Rice',
    description: 'Savory gyro meat served over rice—simple, flavorful, and filling.',
    price: 14.99,
    category: 'Rice Dishes',
    image_url: '/images/menu/gyro-rice.webp',
  },
  {
    id: 'lamb-shank-rice',
    name: 'Lamb Shank with Rice',
    description: 'Slow-cooked lamb shank served over rice for rich, comforting flavor in every bite.',
    price: 14.99,
    category: 'Rice Dishes',
    image_url: '/images/menu/lamb-shank-rice.webp',
  },
  {
    id: 'shawarma-rice',
    name: 'Shawarma with Rice',
    description: 'Well-seasoned chicken shawarma served over rice—classic, bold, and delicious.',
    price: 14.99,
    category: 'Rice Dishes',
    image_url: '/images/menu/shawarma-rice.webp',
  },
  {
    id: 'gyro-sandwich',
    name: 'Gyro Sandwich',
    description: 'A warm pita filled with savory gyro meat—quick, classic, and satisfying.',
    price: 7.99,
    category: 'Sandwiches',
    image_url: '/images/menu/gyro-sandwich.webp',
  },
  {
    id: 'chicken-sandwich',
    name: 'Chicken Sandwich',
    description: 'A flavorful chicken sandwich made fresh to order in warm pita.',
    price: 7.99,
    category: 'Sandwiches',
    image_url: '/images/menu/chicken-sandwich.webp',
  },
  {
    id: 'falafel-sandwich',
    name: 'Falafel Sandwich',
    description: 'Crispy falafel tucked into warm pita—packed with flavor and great for any time.',
    price: 7.99,
    category: 'Sandwiches',
    image_url: '/images/menu/flafel-sandwich.webp',
  },
  {
    id: 'potato-or-beef-sambosa',
    name: 'Potato or Beef Sambosa',
    description: 'Golden, crispy sambosa—perfectly seasoned and fried until crunchy.',
    price: 7.99,
    category: 'Appetizers',
    image_url: '/images/menu/potato-or-beef-sambosa.webp',
  },
  {
    id: 'chicken-wings',
    name: 'Chicken Wings',
    description: 'Crispy chicken wings cooked until golden—perfect for sharing (or not).',
    price: 7.99,
    category: 'Appetizers',
    image_url: '/images/menu/chicken-wings.webp',
  },
  {
    id: 'falafel',
    name: 'Falafel',
    description: 'Crispy, well-seasoned falafel—crunchy outside, tender inside.',
    price: 7.99,
    category: 'Appetizers',
    image_url: '/images/menu/flafel.webp',
  },
]
