import { MenuItem } from './types'

export const menuItems: MenuItem[] = [
  {
    id: '1',
    name: '#1 Gyro Sandwich',
    description: 'Tender gyro meat wrapped in warm pita bread with fresh vegetables and tzatziki sauce',
    price: 1,
    category: 'Sandwiches',
    image_url: '/images/menu/gyro sandwich.png',
  },
  {
    id: '2',
    name: '#2 Chicken Shawarma',
    description: 'Marinated chicken shawarma with garlic sauce, pickles, and fresh vegetables in pita',
    price: 1,
    category: 'Sandwiches',
    image_url: '/images/menu/chickken shawarma sandwich.png',
  },
  {
    id: '3',
    name: '#3 Falafel Sandwich',
    description: 'Crispy falafel balls with tahini sauce, fresh vegetables, and pickles in pita bread',
    price: 1,
    category: 'Sandwiches',
    image_url: '/images/menu/flafel sandwich.png',
  },
  {
    id: '4',
    name: '#4 Burger & Fries',
    description: 'Classic beef burger with lettuce, tomato, onion, and special sauce, served with crispy fries',
    price: 1,
    category: 'Sandwiches',
    image_url: '/images/menu/burger and fries.png',
  },
  {
    id: '5',
    name: '#5 Combo Plate (Chicken Shawarma & Gyros)',
    description: 'A combination of our delicious chicken shawarma and gyro meat served with rice and salad',
    price: 1,
    category: 'Combo Plates',
    image_url: '/images/menu/combo plate.png',
  },
  {
    id: '6',
    name: '#6 Chicken Shawarma Over Rice',
    description: 'Tender marinated chicken shawarma served over fragrant basmati rice with garlic sauce',
    price: 1,
    category: 'Rice Dishes',
    image_url: '/images/menu/chicken shawarma plate.png',
  },
  {
    id: '7',
    name: '#7 Gyros Over Rice',
    description: 'Seasoned gyro meat served over basmati rice with tzatziki sauce and fresh vegetables',
    price: 1,
    category: 'Rice Dishes',
    image_url: '/images/menu/gyro plate.png',
  },
  {
    id: '8',
    name: '#8 Chicken Biryani',
    description: 'Fragrant basmati rice cooked with tender chicken, aromatic spices, and herbs',
    price: 1,
    category: 'Rice Dishes',
    image_url: '/images/menu/biryani.png',
  },
  {
    id: '9',
    name: '#9 Kobideh Kabob',
    description: 'Traditional Afghan ground beef kabob, marinated and grilled to perfection',
    price: 1,
    category: 'Kabobs',
    image_url: '/images/menu/kobideh kabob.png',
  },
  {
    id: '10',
    name: '#10 8 PC Chicken Nugget & Fries',
    description: 'Eight crispy chicken nuggets served with golden french fries and your choice of dipping sauce',
    price: 1,
    category: 'Appetizers',
    image_url: '/images/menu/nugget and fries.png',
  },
  {
    id: '11',
    name: '#11 Chicken Tikka',
    description: 'Tender chicken pieces marinated in yogurt and spices, grilled to perfection',
    price: 1,
    category: 'Kabobs',
    image_url: '/images/menu/chicken tikka kabob.png',
  },
  {
    id: '12',
    name: '#12 Lamb Shank Over Rice',
    description: 'Slow-cooked tender lamb shank served over basmati rice with aromatic spices',
    price: 1,
    category: 'Rice Dishes',
    image_url: '/images/menu/lamb shank rice.png',
  },
  {
    id: '13',
    name: '#13 Sultani Kabob',
    description: 'A combination of tender filet mignon and juicy chicken breast, grilled to perfection',
    price: 1,
    category: 'Kabobs',
    image_url: '/images/menu/sultani kabob.png',
  },
  {
    id: '14',
    name: '#14 Falafel Over Rice',
    description: 'Crispy falafel served over basmati rice with tahini sauce and fresh vegetables',
    price: 1,
    category: 'Rice Dishes',
    image_url: '/images/menu/flafel rice.png',
  },
  {
    id: '15',
    name: '#15 Fish Over Rice',
    description: 'Grilled fish fillet served over basmati rice with lemon and herbs',
    price: 1,
    category: 'Rice Dishes',
    image_url: '/images/menu/fish rice.png',
  },
  {
    id: '16',
    name: '#16 Chicken Wings & Fries',
    description: 'Crispy chicken wings tossed in your choice of sauce, served with golden french fries',
    price: 1,
    category: 'Appetizers',
    image_url: '/images/menu/wings fries.png',
  },
]
